import type { Product } from '../types/product'
import { ProductSearch } from '../components/features/ProductSearch'

const products: Product[] = [
  {
    id: '1',
    title: 'Wireless Noise-Cancelling Headphones',
    description: 'Premium over-ear headphones with 40-hour battery life, active noise cancellation, and Hi-Res audio support.',
    price: 24999,
    originalPrice: 34999,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop',
    rating: 4.5,
    reviewCount: 2847,
    inStock: true,
    category: 'Audio',
  },
  {
    id: '2',
    title: 'Mechanical Keyboard — Cherry MX Blue',
    description: 'Compact 75% layout with RGB backlighting, PBT keycaps, and USB-C connectivity. Built for speed.',
    price: 12999,
    imageUrl: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&h=600&fit=crop',
    rating: 4,
    reviewCount: 1203,
    inStock: true,
    category: 'Accessories',
  },
  {
    id: '3',
    title: 'Ultra-Slim Laptop Stand',
    description: 'Ergonomic aluminum stand with adjustable height. Folds flat for travel. Fits laptops up to 17".',
    price: 4999,
    originalPrice: 6999,
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&h=600&fit=crop',
    rating: 4.8,
    reviewCount: 956,
    inStock: true,
    category: 'Accessories',
  },
  {
    id: '4',
    title: 'Smart Fitness Watch — Series 5',
    description: 'Heart rate monitoring, GPS tracking, sleep analysis, and 7-day battery. Water resistant to 50m.',
    price: 19999,
    originalPrice: 24999,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop',
    rating: 3.5,
    reviewCount: 4312,
    inStock: true,
    category: 'Wearables',
  },
  {
    id: '5',
    title: 'Vintage Leather Messenger Bag',
    description: 'Hand-stitched full-grain leather with brass hardware. Fits 15" laptops. Ages beautifully over time.',
    price: 18900,
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop',
    rating: 5,
    reviewCount: 328,
    inStock: false,
    category: 'Bags',
  },
  {
    id: '6',
    title: 'Portable Bluetooth Speaker',
    description: 'Waterproof 360° sound with deep bass. 20-hour playtime, pairs two for stereo. Clip it anywhere.',
    price: 3499,
    originalPrice: 4999,
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&h=600&fit=crop',
    rating: 4.2,
    reviewCount: 5671,
    inStock: true,
    category: 'Audio',
  },
  {
    id: '7',
    title: 'Ergonomic Wireless Mouse',
    description: 'Vertical design reduces wrist strain. Bluetooth + USB receiver. Silent clicks. 6-month battery.',
    price: 5999,
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&h=600&fit=crop',
    rating: 4.3,
    reviewCount: 1872,
    inStock: true,
    category: 'Accessories',
  },
  {
    id: '8',
    title: 'USB-C Docking Station',
    description: 'Triple display support, 100W power delivery, 10Gbps data transfer. Aluminum unibody design.',
    price: 17999,
    originalPrice: 22999,
    imageUrl: 'https://images.unsplash.com/photo-1625842268584-8f3296236761?w=600&h=600&fit=crop',
    rating: 4.1,
    reviewCount: 634,
    inStock: true,
    category: 'Accessories',
  },
  {
    id: '9',
    title: 'Studio Monitor Headphones',
    description: 'Flat frequency response for mixing and mastering. Velour ear pads. Detachable cable. 250 ohm.',
    price: 14999,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop',
    rating: 4.7,
    reviewCount: 2103,
    inStock: true,
    category: 'Audio',
  },
  {
    id: '10',
    title: 'Smart Home Speaker Hub',
    description: 'Voice-controlled speaker with built-in smart home hub. Multi-room audio. Privacy shutter for mic.',
    price: 9999,
    originalPrice: 12999,
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&h=600&fit=crop',
    rating: 3.9,
    reviewCount: 3417,
    inStock: true,
    category: 'Audio',
  },
  {
    id: '11',
    title: 'Fitness Tracker Band',
    description: 'Lightweight band with step counting, heart rate, sleep tracking, and 14-day battery life.',
    price: 4999,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop',
    rating: 3.8,
    reviewCount: 7823,
    inStock: true,
    category: 'Wearables',
  },
  {
    id: '12',
    title: 'Canvas Laptop Backpack',
    description: 'Water-resistant waxed canvas with padded laptop sleeve. Hidden anti-theft pocket. 25L capacity.',
    price: 8999,
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop',
    rating: 4.6,
    reviewCount: 1567,
    inStock: true,
    category: 'Bags',
  },
  {
    id: '13',
    title: 'Smartwatch Pro — Titanium',
    description: 'Premium titanium case, sapphire crystal, always-on AMOLED display. Cellular connectivity built in.',
    price: 44999,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop',
    rating: 4.4,
    reviewCount: 891,
    inStock: true,
    category: 'Wearables',
  },
  {
    id: '14',
    title: 'Compact Travel Organizer',
    description: 'Tech pouch for cables, chargers, and small gadgets. Clamshell opening. Water-resistant nylon.',
    price: 2999,
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop',
    rating: 4.0,
    reviewCount: 2456,
    inStock: true,
    category: 'Bags',
  },
  {
    id: '15',
    title: 'Wireless Earbuds — ANC Pro',
    description: 'True wireless with hybrid ANC, transparency mode, spatial audio. IPX5 sweat resistant.',
    price: 17999,
    originalPrice: 21999,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop',
    rating: 4.6,
    reviewCount: 6234,
    inStock: true,
    category: 'Audio',
  },
]

export function ProductCardDemo() {
  return (
    <div className="mx-auto max-w-6xl space-y-8">
      <header>
        <h1 className="text-3xl font-bold text-gray-900">Product Search</h1>
        <p className="mt-2 text-gray-600">
          Browse products with search, category filtering, price range controls,
          sorting, and pagination. Try the search bar or filter by category and
          price.
        </p>
      </header>

      <ProductSearch products={products} />
    </div>
  )
}
